name: ci/cd

on:
  push:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # otp_version: [19, 20] Removed due to an incompatibility with rebar3_lfe
        otp_version: [21, 22, 23, 24, 25, 26]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Check rebar3 Version
      run: DEBUG=1 rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Xref Check
      run: rebar3 xref
    - name: Run Tests
      run: rebar3 as test eunit
    - name: Run Tests (ltest runner)
      run: make check-runner-ltest
