name: ci/cd

on:
  push:
    branches: [ master, release/*, task/*, feature/*]
  pull_request:
    branches: [ master, release/*, task/*, feature/*]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23, 24]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Xref Check
      run: rebar3 xref
    - name: Run Tests
      run: rebar3 as test eunit
    - name: Run Tests (ltest runner)
      run: make check-runner-ltest
